version: '3'
name: "auth_services"

services:
  authexchange:
    container_name: authexchange
    image: ${IMAGE}
    ports:
      - 9000:9000
    networks:
      - auth_net
    environment:
      FUSIONAUTH_BASE_URL: http://localhost:9011
      FUSIONAUTH_NET_URL: http://fusionauth:9011
      FUSIONAUTH_CLIENT_ID: 6e4e9805-9690-476f-a7d8-2552992c41e1
      FUSIONAUTH_CLIENT_SECRET: ZyYv1MrS4XjCZKMu0YShVXsGbXoHw57pkXNBcSukY48

  fusionauth:
    container_name: fusionauth
    image: fusionauth/fusionauth-app:1.49.2
    depends_on:
      db:
        condition: service_healthy
      search:
        condition: service_healthy
      smtp:
        condition: service_healthy
    ports:
      - 9011:9011
    networks:
      - auth_net
      - db_net
      - search_net
      - mailcatcher_net
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/fusionauth
      DATABASE_ROOT_USERNAME: ${POSTGRES_USER}
      DATABASE_ROOT_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      FUSIONAUTH_APP_MEMORY: ${FUSIONAUTH_APP_MEMORY}
      FUSIONAUTH_APP_RUNTIME_MODE: ${FUSIONAUTH_APP_RUNTIME_MODE}
      FUSIONAUTH_APP_URL: http://fusionauth:9011
      SEARCH_SERVERS: http://search:9200
      SEARCH_TYPE: elasticsearch
      FUSIONAUTH_APP_KICKSTART_FILE: ${FUSIONAUTH_APP_KICKSTART_FILE}
    volumes:
      - fusionauth_config:/usr/local/fusionauth/config
      - ./kickstart:/usr/local/fusionauth/kickstart
    restart: unless-stopped

  db:
    container_name: postgres
    image: postgres:16.0-bookworm
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - db_net
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data

  search:
    container_name: opensearch
    image: opensearchproject/opensearch:2.11.0
    environment:
      cluster.name: fusionauth
      discovery.type: single-node
      node.name: search
      plugins.security.disabled: true
      bootstrap.memory_lock: true
      OPENSEARCH_JAVA_OPTS: ${OPENSEARCH_JAVA_OPTS}
    healthcheck:
      interval: 10s
      retries: 80
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:9200/
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    volumes:
      - search_data:/usr/share/opensearch/data
    networks:
      - search_net

  smtp:
    container_name: mailcatcher
    image: sj26/mailcatcher:v0.9.0
    ports:
      - "1025:1025"
      - "1080:1080"
    healthcheck:
      interval: 10s
      retries: 80
      test: wget -q -O /dev/null http://mailcatcher:1080/
    networks:
      - mailcatcher_net

networks:
  auth_net:
    driver: bridge
  db_net:
    driver: bridge
  search_net:
    driver: bridge
  mailcatcher_net:
    driver: bridge

volumes:
  db_data:
  fusionauth_config:
  search_data:
