name: auth-stack
version: "3"

services:
  fusionauth:
    container_name: fusionauth
    image: fusionauth/fusionauth-app:latest
    depends_on:
      database:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    environment:
      DATABASE_URL: jdbc:postgresql://database:5432/fusionauth
      DATABASE_ROOT_USERNAME: ${POSTGRES_USER}
      DATABASE_ROOT_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_USERNAME: ${FUSIONAUTH_DATABASE_USERNAME}
      DATABASE_PASSWORD: ${FUSIONAUTH_DATABASE_PASSWORD}
      FUSIONAUTH_APP_MEMORY: ${FUSIONAUTH_APP_MEMORY}
      FUSIONAUTH_APP_RUNTIME_MODE: development
      FUSIONAUTH_APP_URL: http://fusionauth:9011
      SEARCH_SERVERS: http://elasticsearch:9200
      SEARCH_TYPE: elasticsearch
      FUSIONAUTH_APP_KICKSTART_FILE: ${FUSIONAUTH_APP_KICKSTART_FILE}
    networks:
      - auth_net
      - db_net
      - search_net
      - mail_net
    restart: unless-stopped
    ports:
      - 9011:9011
    volumes:
      - fusionauth_config:/usr/local/fusionauth/config
      - ./kickstart:/usr/local/fusionauth/kickstart

  database:
    container_name: database
    image: postgres:12.9
    restart: unless-stopped
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - db_net
    volumes:
      - db_data:/var/lib/postgresql/data

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      cluster.name: fusionauth
      bootstrap.memory_lock: "true"
      discovery.type: single-node
      xpack.security.enabled: false # suppress warnings
      ES_JAVA_OPTS: ${ES_JAVA_OPTS}
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--fail",
          "--write-out",
          "'HTTP %{http_code}'",
          "--silent",
          "--output",
          "/dev/null",
          "http://localhost:9200/",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - search_net
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - search_data:/usr/share/elasticsearch/data

  # SMTP server
  mailcatcher:
    container_name: mailcatcher
    restart: on-failure
    image: dockage/mailcatcher:0.9.0
    ports:
      - "1025:1025" # send
      - "1080:1080" # view
    networks:
      - mail_net

networks:
  auth_net:
    name: auth_net
    driver: bridge
  db_net:
    name: db_net
    driver: bridge
  search_net:
    name: search_net
    driver: bridge
  mail_net:
    name: mail_net
    driver: bridge

volumes:
  db_data:
  fusionauth_config:
  search_data:
